### ISSUE TITLE
Use faster random source on Linux

### ISSUE THREAD

**Issue by epeshk** [dodobrands/primitives#16]
Currently `Uuid.NewTimeBased()` and `Uuid.NewMySqlOptimized()` use `Guid.NewGuid()` as a random source. As [known](https://habr.com/ru/companies/skbkontur/articles/661097/), this is not the fastest way to get random data on Unix-like operating systems.

In .NET 6 `Random.Shared.NextBytes(span)` can be used as a random data source for `Uuid`. It may improve performance up to 10 times.

If there is doubt about the randomness of `Random.Shared`, a new method for generating a non-cryptographic random `Uuid` can be added. The seed of `Random.Shared` has a size of 256 bits, which should be enough to generate an unique identifier.

The `Ulid` library [uses](https://github.com/Cysharp/Ulid/blob/1671834a223d8161f64ce12a834fe858497c8a35/src/Ulid/Ulid.cs#L180) its own [random implementation](https://github.com/Cysharp/Ulid/blob/master/src/Ulid/RandomProvider.cs#L40) with a 64-bit seed for compatibility with older runtimes, but IMHO it's not a good idea to implement custom PRNG due to the subtle performance difference with `Random.Shared`.

**Comment by vanbukin** [comment]
The current implementation relies on the PAL layer, which sits beneath the implementation of methods responsible for generating System.Guid on various platforms. Additionally, it rewrites a portion of the bytes in such a way that the resulting value is optimally stored and utilized as a primary key, allowing modern databases to construct an index in the most efficient manner.

**Comment by vanbukin** [comment]
Due to this, the current implementation is slower than the equivalent one in System.Guid since it incurs overhead in shuffling a portion of the bytes. However, the main performance loss is attributed to the method that returns the current date.

**Comment by vanbukin** [comment]
Taking into account the factors mentioned above, it may not be advisable to allocate time towards actively optimizing the generation of the random component of the value.
